language: clojure

addons:
  apt:
    packages:
      - oracle-java8-set-default

script:
  - lein midje

deploy:
  - provider: script
    skip_cleanup: true
    script: bash -c "lein change :deploy-repositories concat '[[\"releases\" {:url \"https://clojars.org/repo/\" :username :env :password :env}]]'  && lein deploy releases"
    on:
      tags: true
